import { $ } from "bun";
import { canonicalize } from "../lib/canonical-url.ts";

export interface OpenPRSummary {
  number: number;
  title: string;
  body: string;
  files: string[];
  sourceUrls: Set<string>;
  isAutoGenerated: boolean;
}

const URL_REGEX = /https?:\/\/[^\s)\]"']+/g;

export async function loadOpenPRs(): Promise<OpenPRSummary[]> {
  // gh must be authenticated. In CI, GH_TOKEN/GITHUB_TOKEN does that.
  let raw: string;
  try {
    raw =
      await $`gh pr list --state open --limit 100 --json number,title,body,files,labels`.text();
  } catch (e) {
    console.warn("[open-prs] gh CLI failed; assuming no open PRs:", (e as Error).message);
    return [];
  }

  type RawPR = {
    number: number;
    title: string;
    body: string;
    files: { path: string }[];
    labels: { name: string }[];
  };

  const prs = JSON.parse(raw) as RawPR[];

  return prs.map((pr) => {
    const sourceUrls = new Set<string>();
    const matches = (pr.body ?? "").match(URL_REGEX) ?? [];
    for (const u of matches) sourceUrls.add(canonicalize(u));
    return {
      number: pr.number,
      title: pr.title,
      body: pr.body ?? "",
      files: pr.files.map((f) => f.path),
      sourceUrls,
      isAutoGenerated: pr.labels.some((l) => l.name === "auto-generated"),
    };
  });
}

export function countAutoGeneratedOpenPRs(prs: OpenPRSummary[]): number {
  return prs.filter((p) => p.isAutoGenerated).length;
}
