import { $ } from "bun";
import { join } from "path";
import { BLOGS_DIR, REPO_ROOT, config } from "../config.ts";
import type { DraftResult, ScoredCandidate } from "../types.ts";

export interface PROpenResult {
  prNumber: number;
  branch: string;
}

export async function openPRForDraft(
  candidate: ScoredCandidate,
  draft: DraftResult,
): Promise<PROpenResult> {
  const branch = `add-story/${draft.slug}`;
  const filePath = join(BLOGS_DIR, draft.filename);

  // 1. Branch + write file. The PR contains ONLY the new blog post.
  // State updates (seen.json) are committed separately to main by the
  // workflow's post-step, so the agent's bookkeeping doesn't pollute
  // content review.
  await $`git checkout -b ${branch}`.cwd(REPO_ROOT);
  await Bun.write(filePath, draft.markdown);

  // 2. Stage and commit.
  await $`git add ${filePath}`.cwd(REPO_ROOT);
  const commitMsg = `Add story: ${draft.frontmatter.title}\n\nAuto-generated by research agent.\nScore: ${candidate.score.total}/100\nSource: ${candidate.url}`;
  await $`git commit -m ${commitMsg}`.cwd(REPO_ROOT);

  // 3. Push and open PR.
  await $`git push -u origin ${branch}`.cwd(REPO_ROOT);

  const body = renderPRBody(candidate, draft);
  const prOutput =
    await $`gh pr create --title ${`Add story: ${draft.frontmatter.title}`} --body ${body} --label ${config.prLabel}`
      .cwd(REPO_ROOT)
      .text();

  const match = prOutput.match(/\/pull\/(\d+)/);
  const prNumber = match ? parseInt(match[1]!, 10) : -1;

  // 4. Return to default branch (so subsequent loop iterations start clean).
  await $`git checkout -`.cwd(REPO_ROOT).quiet();

  return { prNumber, branch };
}

function renderPRBody(c: ScoredCandidate, d: DraftResult): string {
  const s = c.score;
  return [
    "## Auto-generated story",
    "",
    `**Score: ${s.total}/100** (publish threshold: ${config.publishThreshold})`,
    "",
    "| Dimension | Points |",
    "|---|---|",
    `| Severity | ${s.severity} / 30 |`,
    `| Specificity | ${s.specificity} / 20 |`,
    `| Credibility | ${s.credibility} / 15 |`,
    `| Novelty | ${s.novelty} / 15 |`,
    `| Audience fit | ${s.audienceFit} / 10 |`,
    `| Recency | ${s.recency} / 10 |`,
    "",
    "## Source",
    `- ${c.url}`,
    `- Source platform: \`${c.source}\``,
    `- Published: ${c.publishedAt}`,
    "",
    "## Score notes",
    "```",
    c.scoreNotes,
    "```",
    "",
    "## Review checklist",
    "- [ ] Title is specific and not clickbait",
    "- [ ] Date matches the incident, not just publication date",
    "- [ ] Severity matches the impact tier",
    "- [ ] All five sections present (What/How/Why/Lessons/Prevention)",
    "- [ ] Prevention checklist items are actionable",
    "- [ ] No speculation beyond the source",
    "- [ ] No sensitive data exposed (creds, PII)",
    "",
    "_Generated by `agent/index.ts`. Close this PR to reject; the agent records the decision and won't re-suggest._",
  ].join("\n");
}
