/**
 * AI Horrors research agent — entrypoint.
 *
 * Pipeline:
 *   1. Load state + existing content + open PRs
 *   2. Fetch candidates from all sources (parallel)
 *   3. Keyword filter
 *   4. 3-layer dedup
 *   5. Score
 *   6. Top-N publish-grade candidates → draft → PR
 *   7. Borderline candidates → record as needs_review
 *   8. Persist state, print summary
 *
 * Env:
 *   OPENROUTER_API_KEY — required for drafting (and optional LLM tiebreaker)
 *   OPENROUTER_DRAFT_MODEL — override default draft model (see config.ts)
 *   OPENROUTER_TIEBREAK_MODEL — override default tiebreak model
 *   GITHUB_TOKEN / gh-cli auth — required for PR creation
 *   DRY_RUN=1 — fetch + filter + score, but don't open PRs or mutate state
 *   FORCE_RUN=1 — bypass the open-PR backoff (run even with review backlog)
 *   LLM_DRAFTING=0 — disable LLM drafting (useful for offline runs)
 */

import { config } from "./config.ts";
import { fetchHackerNews } from "./sources/hackernews.ts";
import { fetchReddit } from "./sources/reddit.ts";
import { fetchRss } from "./sources/rss.ts";
import { fetchLobsters } from "./sources/lobsters.ts";
import { filterCandidates } from "./pipeline/filter.ts";
import { loadExistingContent } from "./pipeline/existing-content.ts";
import { loadOpenPRs, countAutoGeneratedOpenPRs } from "./pipeline/open-prs.ts";
import { dedupe } from "./pipeline/dedupe.ts";
import { scoreCandidate } from "./pipeline/score.ts";
import { draftStory, pickFewShotExamples } from "./pipeline/draft.ts";
import { openPRForDraft } from "./pipeline/pr.ts";
import { renderSummary } from "./pipeline/summary.ts";
import { loadState, recordSeen, saveState } from "./lib/state.ts";
import type { Candidate, RunSummary, ScoredCandidate } from "./types.ts";

async function main() {
  const startedAt = new Date().toISOString();
  const summary: RunSummary = {
    startedAt,
    finishedAt: "",
    fetched: 0,
    afterFilter: 0,
    afterDedupe: 0,
    scored: 0,
    publishedThreshold: config.publishThreshold,
    prsOpened: [],
    needsReview: [],
    skipped: [],
    errors: [],
  };

  const state = await loadState();
  const sinceTs = Math.floor(Date.now() / 1000) - config.lookbackDays * 86_400;

  console.log(
    `[agent] dry_run=${config.dryRun} force_run=${config.forceRun} lookback=${config.lookbackDays}d model=${config.draftModel}`,
  );
  console.log(
    `[agent] state: ${state.seen.length} seen entries loaded (last_run=${state.last_run ?? "never"})`,
  );

  // 1. Load context.
  const existing = loadExistingContent();
  console.log(`[agent] loaded ${existing.slugs.size} existing blog posts`);

  const openPRs = await loadOpenPRs();
  const autoOpen = countAutoGeneratedOpenPRs(openPRs);
  console.log(`[agent] open PRs: ${openPRs.length} (${autoOpen} auto-generated)`);
  if (autoOpen >= config.maxOpenAutoPRs) {
    if (config.forceRun) {
      console.log(
        `[agent] force_run=1 — bypassing backoff (${autoOpen} auto-PRs already open, cap=${config.maxOpenAutoPRs})`,
      );
    } else {
      summary.errors.push(
        `Backoff: ${autoOpen} auto-generated PRs already open (cap=${config.maxOpenAutoPRs}). Skipping run. Re-trigger with force_run=true to override.`,
      );
      summary.finishedAt = new Date().toISOString();
      console.log(renderSummary(summary));
      return;
    }
  }

  // 2. Fetch.
  const fetched = await fetchAll(sinceTs);
  summary.fetched = fetched.length;
  console.log(`[agent] fetched ${fetched.length} candidates`);

  // 3. Filter.
  const filtered = filterCandidates(fetched);
  summary.afterFilter = filtered.kept.length;
  for (const d of filtered.dropped) {
    summary.skipped.push({ url: d.candidate.url, reason: d.reason });
  }
  console.log(`[agent] after filter: ${filtered.kept.length}`);

  // 4. Dedup.
  const dd = dedupe(filtered.kept, state, existing, openPRs);
  summary.afterDedupe = dd.fresh.length;
  for (const d of dd.duplicates) {
    summary.skipped.push({ url: d.candidate.url, reason: `dup: ${d.reason}` });
    if (!config.dryRun) {
      recordSeen(state, {
        url_hash: d.candidate.urlHash,
        url: d.candidate.url,
        title: d.candidate.title,
        first_seen: startedAt,
        outcome: "skipped_duplicate",
        reason: d.reason,
      });
    }
  }
  console.log(`[agent] after dedup: ${dd.fresh.length}`);

  // 5. Score.
  const scored: ScoredCandidate[] = dd.fresh
    .map((c) => scoreCandidate(c, existing.titles))
    .sort((a, b) => b.score.total - a.score.total);
  summary.scored = scored.length;
  for (const s of scored) {
    console.log(`  [${s.score.total}] ${s.verdict}  ${s.title}`);
  }

  // 6. Open PRs for top-N "publish" candidates.
  const toPublish = scored.filter((c) => c.verdict === "publish").slice(0, config.maxPRsPerRun);
  for (const c of toPublish) {
    try {
      if (config.dryRun || !config.llmDrafting) {
        summary.prsOpened.push({ number: -1, slug: "(dry-run)", score: c.score.total });
        continue;
      }
      const fewShot = pickFewShotExamples(c, existing.rawDocs);
      const draft = await draftStory(c, fewShot);
      const pr = await openPRForDraft(c, draft);
      summary.prsOpened.push({ number: pr.prNumber, slug: draft.slug, score: c.score.total });
      recordSeen(state, {
        url_hash: c.urlHash,
        url: c.url,
        title: c.title,
        first_seen: startedAt,
        outcome: "pr_opened",
        pr_number: pr.prNumber,
      });
      console.log(`[agent] opened PR #${pr.prNumber} for ${draft.slug}`);
    } catch (e) {
      const msg = (e as Error).message;
      summary.errors.push(`PR for ${c.url}: ${msg}`);
      recordSeen(state, {
        url_hash: c.urlHash,
        url: c.url,
        title: c.title,
        first_seen: startedAt,
        outcome: "errored",
        reason: msg,
      });
      console.error(`[agent] PR creation failed:`, msg);
    }
  }

  // 7. Record needs_review and skips that didn't make the cut.
  for (const c of scored) {
    if (toPublish.includes(c)) continue;
    const outcome = c.verdict === "needs_review" ? "needs_review" : "skipped_score";
    if (c.verdict === "needs_review") {
      summary.needsReview.push({
        slug: "(no draft)",
        score: c.score.total,
        reason: c.title,
      });
    }
    if (!config.dryRun) {
      recordSeen(state, {
        url_hash: c.urlHash,
        url: c.url,
        title: c.title,
        first_seen: startedAt,
        outcome,
        reason: c.scoreNotes.slice(0, 200),
      });
    }
  }

  // 8. Persist state + render summary.
  state.last_run = startedAt;
  if (!config.dryRun) await saveState(state);

  summary.finishedAt = new Date().toISOString();
  const md = renderSummary(summary);
  console.log("\n" + md);

  // Write summary as workflow artifact, if running in CI.
  if (process.env.GITHUB_STEP_SUMMARY) {
    await Bun.write(process.env.GITHUB_STEP_SUMMARY, md);
  }
}

async function fetchAll(sinceTs: number): Promise<Candidate[]> {
  const results = await Promise.allSettled([
    fetchHackerNews(sinceTs),
    fetchReddit(sinceTs),
    fetchRss(sinceTs),
    fetchLobsters(sinceTs),
  ]);
  const out: Candidate[] = [];
  const seen = new Set<string>();
  for (const r of results) {
    if (r.status !== "fulfilled") {
      console.warn("[agent] source failed:", r.reason);
      continue;
    }
    for (const c of r.value) {
      if (seen.has(c.urlHash)) continue;
      seen.add(c.urlHash);
      out.push(c);
    }
  }
  return out;
}

main().catch((e) => {
  console.error("[agent] fatal:", e);
  process.exit(1);
});
